name: Cache Test

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/test-cache
          key: cache-3e9899c

      - name: prime-cache-3e9899c
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
